= OpenFaaS Idris 2 template =

An https://github.com/openfaas[OpenFaaS] template for writing functions in https://www.idris-lang.org[Idris 2].

https://github.com/stefan-hoeck/idris2-pack[Pack] is used to manage Idris 2 dependencies.

`of-watchdog` mode used is https://github.com/openfaas/of-watchdog#3-streaming-fork-modestreaming---default[Streaming fork], because I couldn't find an HTTP server that could work with language arbitrary back ends.

Idris 2 language back end is https://github.com/cisco/chezscheme[Chez Scheme]. More back ends coming soon.

== Prerequisites ==

* https://docs.openfaas.com/cli/install/[OpenFaaS CLI]: makes `faas` command available.

== Usage ==

=== Pull OpenFaaS template ===

To create Idris 2 Functions with this template, use the following command once:
[source, bash]
----
faas template pull https://github.com/ccfontes/openfaas-idris2-pack-template
----
If you ever need to update the template, simply run the command above with the `--overwrite` flag.

=== Create an Idris 2 Function ===

Create Idris 2 Functions as with the following command example:
[source, bash]
----
faas new --lang idris2 my-idris2-function
----
A new project is created for a function defined as `my-idris2-function`. It will contain a `Function.Handler` namespace that is required for the template to work properly. The requirement for this namespace is to have a top-level function defined as `handler : String -> String`.

== Function libraries ==

You can add new libraries using https://github.com/stefan-hoeck/idris2-pack[Pack], which is already configured in the template. +
To add new libraries, edit to `function.ipkg` file present in the root directory of your Function. Example:

[source]
----
depends = dinwiddy
----
This adds https://github.com/stefan-hoeck/idris2-pack-db[Pack supported] https://github.com/Bobbbay/dinwiddy[dinwiddy] library package to the project. This way also supports adding https://idris2.readthedocs.io/en/latest/reference/packages.html[library packages shipped with Idris 2].

It is also possible to add external library packages that aren't supported yet by Pack. To do this, create a file named `pack.toml` in the root directory of your Function, as such:

[source]
----
[hashmap]
type   = "github"
url    = "https://github.com/Z-snails/idris2-hashmap"
commit = "58f5a2d2c0a7bb082666d6ce668ee242185a52bf"
ipkg   = "hashmap.ipkg"
----
Then in `function.ipkg`, add `hashmap` library package:
[source]
----
depends = dinwiddy, hashmap
----

== Function examples ==

See the link:function-examples[function-examples] directory to find a fully working set of OpenFaaS Functions written in Idris 2.

== TODO ==

* Support multiple Idris 2 language back ends: https://idris2.readthedocs.io/en/latest/backends/javascript.html[Node], https://github.com/mmhelloworld/idris-jvm[JVM], https://github.com/madman-bob/idris2-python[Python]
* Run Function as non-root user

== Production expectations ==

Hopefully, this effort will bring Idris 2 closer to being production ready on a serverless scenario.

A considerable amount of web stack plumbing requirements is removed by running your Idris 2 programs in serverless, but there are still the following caveats:

* Writing FFI bindings for libraries from other languages that you wish to use.
* Not a lot of code examples in stackoverflow, but we're already seeing Large Language Models like ChatGPT giving some good answers.
* Code generator to some other language may not live to your expectations.

== Apple Silicon support ==

I will not focus on supporting Apple Silicon Docker image. Someone might find useful the following information from the https://github.com/idris-lang/Idris2/blob/main/INSTALL.md#installing-chez-scheme-on-apple-silicon[Idris 2 documentation]:

> The official version of chez scheme does not yet support Apple Silicon. So, on macOS with Apple Silicon (e.g. M1 and M2 macs), you will need to build and install the Racket fork of chez scheme.

Install Chez Scheme on Apple Silicon:
```
git clone git@github.com:racket/ChezScheme.git
cd ChezScheme
git submodule init
git submodule update
arch=tarm64osx
./configure --pb
make ${arch}.bootquick
./configure --threads
make
sudo make install
```

== Manual tests ==

This information is for OpenFaaS template developers.

Check this template's Idris build:
[source, bash]
----
idris2 Index.idr --exec main
----

Check this template's docker build:
[source, bash]
----
docker-compose up
----

== Contributing ==

Contributions are welcome! If you find a bug or have an idea for a new feature, please open an issue or submit a pull request.

== link:LICENSE[License] ==

Copyright (c) 2023 Carlos da Cunha Fontes

The MIT License
