= OpenFaaS Functions in Idris 2 =

Hello world OpenFaaS Function in Idris 2.

See the link:idris2-hello[idris2-hello] and link:idris2-pack[idris2-pack] directories to find the Idris 2 Function code examples.

The following documentation explains how to run these Functions in OpenFaaS.

See https://docs.openfaas.com/tutorials/first-python-function/[OpenFaaS website] for more detailed and up to date documentation.

== Prerequisites ==
* Docker
* https://docs.openfaas.com/cli/install/[OpenFaaS CLI]
* OpenFaaS: to try in localhost, maybe provision https://github.com/openfaas/faasd[faasd]

== Get OpenFaaS template ==

Get the Idris 2 OpenFaaS template:
[source, bash]
----
faas template pull https://github.com/ccfontes/openfaas-idris2-pack-template
----

== Environment variables

[source, bash]
----
export DOCKER_REGISTRY_IMG_ORG_PATH=<registry org path>
----
Check link:function-examples/stack.yml[function-examples/stack.yml] to find out how `DOCKER_REGISTRY_IMG_ORG_PATH` is used.

== Building and deploying your function ==

To build and deploy the Functions to OpenFaaS, run the following command:
[source, bash]
----
faas up
----

== Testing a function ==

Test a Function using the OpenFaaS UI or with the following command:
[source, bash]
----
echo "world" | faas invoke idris2-hello
----
Should ouput "Hello, world" string to the terminal.
