version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  idris2-hello:
    lang: idris2
    handler: ./idris2-hello
    image: ${DOCKER_REGISTRY_IMG_ORG_PATH}/idris2-hello
  idris2-pack:
    lang: idris2
    handler: ./idris2-pack
    image: ${DOCKER_REGISTRY_IMG_ORG_PATH}/idris2-pack
  idris2-node-hello:
    lang: idris2
    handler: ./idris2-node-hello
    image: ${DOCKER_REGISTRY_IMG_ORG_PATH}/idris2-node-hello
  idris2-node-pack-yarn:
    lang: idris2
    handler: ./idris2-node-pack-yarn
    image: ${DOCKER_REGISTRY_IMG_ORG_PATH}/idris2-node-pack-yarn

